module.exports={
    datadriven:{
         "smartfiltertitle" : "SMART FILTERS",
         "error1"           : "Common filters is required",
         "error2"           : 'Should be in a format: "keyword"~number, e.g. "HSBC"~5. Multiple filters are allowed with new lines',
         "error3"           : ' Should be in a format: "keyword"~number, e.g. "HSBC"~5. Multiple filters are allowed with new lines ',
         "error4"           : 'Should be in format: "keyword", e.g. "HSBC". Multiple filters are allowed with new lines. ',
         "error5"           : 'Sorry! Cannot proceed with extra blank positive filter(s).',
         "error6"           : 'Enter value from 1 to 5',
         "error7"           : 'It cannot be blank',
         "newsfeednamef1"   : "Test1 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef2"   : "Test2 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef3"   : "Test3 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef4"   : "Test4 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef5"   : "Test5 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef6"   : "Test6 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef7"   : "Test7 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef8"   : "Test8 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef9"   : "Test9 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef10"  : "Test10 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef11"  : "Test11 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef12"  : "Test12 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef13"  : "Test13 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef14"  : "Test14 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef15"  : "Test15 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef16"  : "Test16 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef17"  : "Test17 news letter"+ Math.floor(Math.random() * 9),
         "newsfeednamef18"  : "Test18 news letter"+ Math.floor(Math.random() * 9),
         "commonfilter1"    : '"the"~1',
         "positivefilter1"  : '"the"',
         "invalidfilter1"   : '"the"',
         "invalidfilter2"   : '"the',
         "overallweightage" :"1",
         "value1"           :"2",
         "value2"            :"3",
         "overallwninvalid" :"6",
         "positivefilterscount" :"2", 
         "defaulttitleboost"    :"1",
         "defaultthreshold"     :"70",
         "titleboostvalue"      :"10",
         "Articlesize"          :"9999",
         "Articlesize1":        "100"

    }
}